import type { Metadata } from "next";
import {  Karla } from "next/font/google";
import Header from "./components/header/Header";
import { CSSProperties } from "react";
import "./globals.scss";

const karla = Karla({ subsets: ["latin"],weight:['200','300','400','500','600','700','800'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className} style={{'--fontMain':karla.style.fontFamily} as CSSProperties}>
				<Header/>
				{children}
			</body>
    </html>
  );
}
