import type { Metadata } from "next";
import {  Karla } from "next/font/google";
import { CSSProperties } from "react";
import Header from "./components/header/Header";
import './globals.scss';
import Login from "./components/login/Login";
import { AnimatePresence } from "framer-motion";
import Presence from "./components/hoc/presence/Presence";
const karla = Karla({ subsets: ["latin"],weight:['200','300','400','500','600','700','800'] });

export const metadata: Metadata = {
  title: "Mawissuh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className} style={{'--fontMain':karla.style.fontFamily} as CSSProperties}>
				<div className="main-container">
					<Header/>
					<Login/>
					<div className="decor_badges">
						<img src="/graphics/badge.png" alt="" className="decor_bg-badge" />
						<img src="/graphics/badge.png" alt="" className="decor_bg-badge glitched" />
					</div>
						<Presence>
							{children}
						</Presence>
				</div>
			</body>
    </html>
  );
}
